### ISSUE TITLE
初始化参数中的SchedWall和erlang:statistics(scheduler_wall_time)的结果可能相同

### ISSUE THREAD

**Issue by gbember** [ferd/recon#39] opened 2016-03-09 06:29 UTC
** exception error: an error occurred when evaluating an arithmetic expression
     in function  recon_lib:'-scheduler_usage_diff/2-fun-0-'/1 (e:/mywork/recon/src/recon_lib.erl, line 221)
     in call from lists:map/2 (lists.erl, line 1237)
     in call from recon:'-node_stats/4-fun-0-'/1 (e:/mywork/recon/src/recon.erl, line 430)
     in call from recon_lib:time_fold/6 (e:/mywork/recon/src/recon_lib.erl, line 206)
     in call from recon:node_stats/4 (e:/mywork/recon/src/recon.erl, line 445)

**Comment by ferd** [comment] 2016-03-09 06:52
Duplicate of https://github.com/ferd/recon/pull/35

**Closed** 2016-04-05 21:31 UTC
